#!/usr/bin/env bash
#
# Build tests for FYSETC_S6
#

# exit on first failure
set -e

# Build examples
restore_configs
use_example_configs FYSETC/S6
opt_set X_DRIVER_TYPE TMC2209
opt_set Y_DRIVER_TYPE TMC2130
exec_test $1 $2 "Fysetc S6 Default Configuration plus TMC steppers"

# cleanup
restore_configs
